## ===== SERVER =====
#server.port=8080
#spring.application.name=bharatpos-backend
#
## ===== DATABASE =====
#spring.datasource.url=jdbc:postgresql://localhost:5432/bharatpos_db
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## ===== JPA =====
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
## ===== JWT =====
#bharatpos.jwt.secret=BharatPOS_Super_Secret_Key_2026_India_Retail_Software_JWT_256bit_Key
#bharatpos.jwt.expiration=900000
#bharatpos.jwt.refresh-expiration=604800000
#
## ===== CORS =====
#bharatpos.cors.allowed-origins=http://localhost:5173,https://bharatpos-frontend-ft4m.vercel.app
#
## ===== ACTUATOR =====
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=when-authorized
#
## ===== LOGGING =====
#logging.level.com.bharatpos=DEBUG
#logging.level.org.springframework.security=WARN








# ===== SERVER =====
server.port=${PORT:8080}
spring.application.name=bharatpos-backend

# ===== DATABASE =====
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===== JWT =====
bharatpos.jwt.secret=${JWT_SECRET}
bharatpos.jwt.expiration=900000
bharatpos.jwt.refresh-expiration=604800000

# ===== CORS =====
bharatpos.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173}

# ===== ACTUATOR =====
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# ===== LOGGING =====
logging.level.com.bharatpos=INFO
logging.level.org.springframework.security=WARN